# quarto render --profile pracs
# https://quarto.org/docs/books/book-output.html
# https://quarto.org/docs/projects/profiles.html
project:
  pre-render:
    - scripts/pracs-pre.py
  post-render:
    - scripts/pracs-post.py
  output-dir: _answers 
  render:
    - "practicals/*.qmd"
  resources:
    - "img/"
    - "practicals/img/"
    - "!assessments"
    - "!data/"
    - "!lectures/"
    - "!sessions/"
    - "!setup/"
    - "!ref/"
qna:
  ipynb: answer
  pdf: answer
