# https://quarto.org/docs/books/book-output.html
project:
  pre-render:
    - scripts/pre.py
  post-render:
    - scripts/post.py
  type: website
  output-dir: _site
  preview:
    port: 4200
  render:
    - "*.qmd"
  resources:
    - "bib/"
    - "img/"
    - "!data/"
execute:
  freeze: auto

metadata-files:
  - _website.yml

qna:
  ipynb: question
  html: question
  #pdf: question

format:
  html:
    theme:
      - minty
      - css/casa-report.scss
      - css/casa-web.scss
    code-copy: true
    code-link: true
    code-overflow: wrap
    #cover-image: cover.png
    toc: true
    toc-title: "On this page"
    toc-depth: 2
    toc_float:
      collapsed: false
      smooth_scroll: true
  revealjs:
    # multiplex: true 
    # embed-resources: true
    logo: "/img/logo/full.svg"
    template-partials:
      - /inc/title-slide.html
    transition: none
    slide-number: false
    preview-links: auto
    theme:
      - css/casa-slides.scss # Must be valid *relative* path
    footer: "[CC BY-NC-SA 4.0 2022-2025 | Jon Reades](https://creativecommons.org/licenses/by-nc-sa/4.0/)"
    title-slide-attributes:
      data-background-image: "/img/web/title-slide.png"
      data-background-size: stretch
      data-background-opacity: "0.08"
      data-background-color: "#4e3c56"
highlight-style: pygments
code-copy: true
code-line-numbers: true
slide-level: 2
history: false
from: markdown+emoji
filters:
  - code-visibility
lightbox: auto

bibliography: ref/Readings.bib
csl: ref/chicago-author-date.csl
