# Format {.unnumbered}

## Overview {.unnumbered}

We have 'flipped' the classroom for this module so we expect you to come to 'lecture' (***except*** in Week 1!) having already watched the assigned videos and completed the assigned readings. You may be called upon to present a short summary of the key points in, and relevance of, an assigned video or reading to the rest of the class.

This means that there is a mix of 'asynchronous' (work that you do in your own time) and 'synchronous' (work that we do during scheduled hours) interaction. Synchronous activities will normally be recorded for review afterwards, but you should bear in the mind the following: 1) we cannot be responsible for equipment failure; and 2) a 2-hour video of a group discussion and live coding session will be rather less educational and informative than actually *being there*.

In short, recordings should not be used as a substitute for attendance save in exceptional circumstances.

## Preparation {.unnumbered}

The nature and amount of preparation will vary from week to week, but may include:

- Readings from both academic and non-academic sources.
- Recorded lectures from CASA staff.
- Recorded videos from non-CASA staff.
- Short Moodle quizzes to test your completion of readings and videos.
- Contributions to weekly tasks (e.g. summaries, Q&A, etc.)

## Class {.unnumbered}

The 'lecture' in your timetable will be used for a mix of discussion and 'live c
oding' (eeek!) using the following framework:

- We will review questions and issues arising from the previous week's practical
 session.
- We will use ***your*** contributions to the week's Padlet to prioritise discus
sion around concepts and readings with which students are struggling or wish to
engage further.
- We will have a 'live coding' session following an 'I do/We do' format: we will
 employ concepts covered in the week's preparation activities, as well as approa
ches that will be explored further in the practical, to look a real-world data s
et *together* using code.

So we're going to call these **workshops** instead!

## Practicals {.unnumbered}

In order to make use of these materials you will need to download and install the [Spatial Data Science computing environment](https://github.com/jreades/sds_env/).

Practicals are run in small groups... you will be informed of your group... you should download the relevant Jupyter notebook at the start of class.

## Readings {.unnumbered}
