---
filters: 
  - lightbox
lightbox:
  match: auto
  effect: fade
  desc-position: right
  loop: false
title: "Getting Help"
---

We *all* need help from time to time, and while we will *always* do our best to support you because we know that this module is hard for students who are new to programming, the best way to 'get help' will *also* always be taking steps to 'help yourself' first.

## How to Help Yourself 

Here are at least six things that you can do to 'help yourself':

- Use the dedicated **#fsds channel** on [Slack]({{< var module.slack >}})--this provides a much richer experience than the Moodle Forum and should be your **primary means of requesting help** outside of scheduled teaching hours.
- Do the readings--regardless of whether we ask you questions in class about them (or not), the readings are designed to support the module's learning outcomes, so if you are struggling with a concept or an idea then please look to the week's readings! You should also review the [full bibliography](./references.qmd) while developing your thinking for the final project.
- Use [Google](https://letmegooglethat.com/?q=python+help)--this is one course where saying "I googled it..." will be taken as a good sign! Probalby the biggest difference between a *good* programmer and a *new* programmer is that the good one knows which terms to type into Google to get the answer that they need right away.
- Use [Stack Overflow](https://stackoverflow.com/questions/tagged/python)--as you become a better programmer you'll start to understand how to frame your question in ways that produce the right answer right away, but whether you're a beginner or an expert Stack Overflow is your friend.
- Make use of [Drop-in Hours](https://jreades.youcanbook.me/) (see also below)--there is no extra credit for struggling in silence, and we can't help you if we don't know that you're lost! That doesn't mean that we can simply 'give' you the answers to challenging questions, but we will do everything that we can to support your learning. Many of the same advice applies here as on our *other* [Getting Help](https://jreades.github.io/sds_env/skills/help.html) page (with the [Soft Skills](https://jreades.github.io/sds_env)).
- Practice like it's a language--set yourself little problems or tasks and see if you can apply what you've learned in class to a problem in a different class, or a friend's problem, or just something you're curious about! In the same way that practicing your Chinese or French with native speakers will help you to learn those languages, so will practicing your Python.
- Sign up for online classes--realistically, you will have a lot on your plate, but if you want or need more practice with Python and are strugging to come up with your own problems to work through then there is a wealth of options out there. You might also find that a different explanation or challenge resonates and gives you new insight into how to code.

**Remember**: when you are learning to code there is no such thing as a *stupid* question. Sometimes students have *lazy* questions when they are frustrated and just want to know 'the answer', but anyone finding themselves stuck on a particular problem has a 100% chance that someone else in the class has the *same* problem as well but hasn't quite worked up the courage to ask. So please: ask.

## You Can Book Me

<iframe src="https://jreades.youcanbook.me/?noframe=true&skipHeaderFooter=true" id="ycbmiframejreades" style="width:100%;height:1000px;border:0px;background-color:transparent;" frameborder="0" allowtransparency="true"></iframe><script>window.addEventListener && window.addEventListener("message", function(event){if (event.origin === "https://jreades.youcanbook.me"){document.getElementById("ycbmiframejreades").style.height = event.data + "px";}}, false);</script>
