# Dimensions in Data

### Preparation

#### Lectures

- Watch: [The Data Space](https://web.microsoftstream.com/video/9c365da5-81b4-43f8-8296-1
6086f3f5887) ([Notes](https://github.com/jreades/i2p/blob/master/lectures/9.1-Data_Space.
md))
- Watch: [Transformation](https://web.microsoftstream.com/video/070225ac-285b-4408-8c2a-3
5e223b79845) ([Notes](https://github.com/jreades/i2p/blob/master/lectures/9.2-Transformat
ion.md))
- Watch: [Dimensionality](https://web.microsoftstream.com/video/9b47ffbb-de09-4538-bf84-6
6decfd1250b) ([Notes](https://github.com/jreades/i2p/blob/master/lectures/9.3-Dimensional
ity.md))

#### Readings

- [@Bunday:0000] A Final Tale or You Can Prove Anything with Figures [URL](https://www.uc
l.ac.uk/~ucahhwi/AFinalTale.pdf)
- [@Harris:2019] The Certain Uncertainty of University Rankings [URL](https://rpubs.com/p
rofrichharris/uni-rankings)
- [@Cima:2014] The Most and Least Diverse Cities in America, Priceonomics [URL](https://p
riceonomics.com/the-most-and-least-diverse-cities-in-america/) ([PDF with Figures](https:
//github.com/jreades/i2p/blob/master/docs/The_Least_Segregated_Cities_in_America.pdf))
- [@lu:2013] Are statisticians cold-blooded bosses? a new perspective on the ‘old’ concep
t of statistical population [DOI](https://doi.org/10.1111/j.1467-9639.2012.00524.x)

#### Contribution

- Padlet: [Collaborative Agenda]

#### Quiz!

- Complete the [short Moodle quiz](https://moodle.ucl.ac.uk/mod/quiz/view.php?id=2621322)
 associated with this week's activities.

### Workshop

- Reviewing the **Collaborative Agenda**
- Discussion of **Readings**
- **Live Coding**

### Practical

The practical can then be [downloaded from GitHub](https://github.com/jreades/i2p/blob/master/practicals/Practical-09-Dimensions_in_Data.ipynb).
