# Numeric Data

:::{.callout-warning}
## Changes before 22/23

- [ ] Add Learning Outcomes for each week
- [ ] Highlight differences from CASA0007; Airbnb data from CASA0005
:::


## Lectures

- Watch: [Logic](https://web.microsoftstream.com/video/b9684684-5210-4917-8066-c7c247872051) ([Notes](https://github.com/jreades/i2p/blob/master/lectures/5.1-Logic.md))
- Watch: [Randomness](https://web.microsoftstream.com/video/18ee48e3-81d9-42d2-9e24-d434a9aa06ce) ([Notes](https://github.com/jreades/i2p/blob/master/lectures/5.2-Randomness.md))
- Watch: [Data Files](https://web.microsoftstream.com/video/465db9d5-fc82-42f7-ada4-089a01de1d7b) ([Notes](https://github.com/jreades/i2p/blob/master/lectures/5.3-Files.md))
- Watch: [Pandas](https://web.microsoftstream.com/video/ce84fd59-b44f-40cb-804b-593613053e24) ([Notes](https://github.com/jreades/i2p/blob/master/lectures/5.4-Pandas.md))

## Readings

- [@dignazio:2020, chap. 4] **What Gets Counted Counts** in *Data Feminism*; [Pre-review
URL](https://bookbook.pubpub.org/pub/rykaknh1)
- [@Wachsmuth:2018] [DOI](https://doi.org/10.1177%2F0308518X18778038)
- [@Harris:2018] [URL](https://www.theguardian.com/commentisfree/2018/feb/12/profiteers-k
illing-airbnb-erode-communities)

## Contribution

- Padlet: [Collaborative Agenda]

## Class

- Brief Discussion of **Assessments*
- Reviewing the **Collaborative Agenda**
- Discussion of **Readings**
- **Live Coding**

## Practical

:::{.callout-warning}
## Changes before 22/23
- [ ] Add Learning Outcomes for each week
- [ ] Standardise delivery by TAs where practicals are TA-led (e.g. FSDS): clearer guidance on how to take students through each week.
- [ ] Clearer articulation of difficulty levels/targets for components *within* each week’s practicals.
- [ ] Make links between lecture and practical content explicit; ideally trace a question through the whole process (*e.g.* “If I wanted to know if and where blue plaques are clustered in London how would I find out?”)
:::

The practical can be [downloaded from GitHub](https://github.com/jreades/i2p/blob/master/practicals/Practical-05-Numeric_Data.ipynb).
