# Grouping Data

:::{.callout-warning}
## Changes before 22/23
- [ ] Add Learning Outcomes for each week
- [ ] Point to clustering code and show DBSCAN, k-Means, etc. as applied to the Airbnb data. 
- [ ] Stress different view of clustering as part of a pipeline, not an absolute “just k-means it”; link to thinking about paradigms in CASA0001; 
- [ ] thinking about proxies (why would you find ppsqm more/less useful than price? what are you *really* measuring? 

Connects to both CASA0001 *and* CASA0007 and CASA0005.
:::


## Lectures

- Watch: [Classification](https://web.microsoftstream.com/video/1a88749d-2dca-4bc6-9990-3
227a253bfb0) ([Notes](https://github.com/jreades/i2p/blob/master/lectures/10.1-Classifica
tion.md))
- Watch: [Clustering](https://web.microsoftstream.com/video/77b1ad5c-bece-4154-89b3-cb1e4
2877cae) ([Notes](https://github.com/jreades/i2p/blob/master/lectures/10.2-Clustering.md)
)

## Readings

- [@shapiro:2017] [URL](https://medium.com/topos-ai/rethinking-distance-in-new-york-city-d17212d24919)
- [@wolf:2021] [DOI](https://doi.org/10.1177%2F0309132520924722)
- [@singleton2019] [DOI](https://doi.org/10.1111/gean.12194)


## Contribution

- Padlet: [Collaborative Agenda]

## Quiz!

- Complete the short Moodle quiz associated with this week's activities.

## Class

- Reviewing the **Collaborative Agenda**
- Discussion of **Readings** and **Reflections**

## Practical

:::{.callout-warning}
## Changes before 22/23
- [ ] Add Learning Outcomes for each week
- [ ] Standardise delivery by TAs where practicals are TA-led (e.g. FSDS): clearer guidance on how to take students through each week.
- [ ] Clearer articulation of difficulty levels/targets for components *within* each week’s practicals.
- [ ] Make links between lecture and practical content explicit; ideally trace a question through the whole process (*e.g.* “If I wanted to know if and where blue plaques are clustered in London how would I find out?”)
:::

The practical can then be [downloaded from GitHub](https://github.com/jreades/i2p/blob/master/practicals/Practical-10-Grouping_Data.ipynb).
