# Foundations (Pt. 2)

### Preparation

#### Code Camp

*All* students should complete/revisit [Code Camp](https://mybinder.org/v2/gh/kingsgeocom
p/code-camp-env/notebook-v1.0?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%25
2Fkingsgeocomp%252Fcode-camp%26urlpath%3Dtree%252Fcode-camp%252F%26branch%3Dmaster) Noteb
ooks 8–11.

**Note:** there is an issue with the GeoJSON tasks in Notebooks 8 and 9. We can discuss i
n the Workshop.

#### Lectures

This week we start to move beyond [Code Camp](https://kingsgeocomputation.org/teaching/co
de-camp/code-camp-python/). So although you should recognise many of the _parts_ that we
discuss,  you'll see that we start to put them together in a new way:

- Watch: [Dictionaries](https://web.microsoftstream.com/video/041f9734-9368-429c-8f91-220
8f9c2ba07) ([Notes](https://github.com/jreades/i2p/blob/master/lectures/3.1-Dictionaries.
md))
- Watch: [LOLs](https://web.microsoftstream.com/video/129b862b-cb1b-41ab-a6ad-d526eff3fd2
0) ([Notes](https://github.com/jreades/i2p/blob/master/lectures/3.2-LOLs.md))
- Watch: [DOLs to Data](https://web.microsoftstream.com/video/28266460-26b2-4455-ab42-145
6f483a412) ([Notes](https://github.com/jreades/i2p/blob/master/lectures/3.3-DOLs_to_Data.
md))
- Watch: [Functions](https://web.microsoftstream.com/video/3bd3fe3a-5dea-4ac8-a3e2-49ab50
b862aa) ([Notes](https://github.com/jreades/i2p/blob/master/lectures/3.4-Functions.md))
- Watch: [Packages](https://web.microsoftstream.com/video/0ef82489-8c35-4532-a459-596d8e8
f9633) ([Notes](https://github.com/jreades/i2p/blob/master/lectures/3.5-Packages.md))

#### Readings

- [@Etherington:2016] [DOI](https://doi.org/10.1080/03098265.2015.1086981)
- [@Donoho:2017] [DOI](https://doi.org/10.1080/10618600.2017.1384734)
- [@Unwin:1980] [DOI](https://doi.org/10.1080/03098268008708772)

#### Contribution

- Padlet: [Collaborative Agenda]

#### Quiz!

- Complete the [short Moodle quiz](https://moodle.ucl.ac.uk/mod/quiz/view.php?id=24300940
) associated with this week's activities.

### Workshop

- Reviewing the **Collaborative Agenda**
- Discussion of **Readings**
- **Live Coding**

### Practical

The practical can then be downloaded from [GitHub](https://github.com/jreades/i2p/raw/master/practicals/Practical-03-Foundations_2.ipynb).
