# Visualising Data

### Preparation

#### Lectures

- Watch: [Linking Data](https://web.microsoftstream.com/video/05759776-10b9-4476-9949-c7c
0fbeef298) ([Notes](https://github.com/jreades/i2p/blob/master/lectures/8.1-Linking_Data.
md))
- Watch: [Linking Spatial Data](https://web.microsoftstream.com/video/4bf27eaa-90d8-4628-
81ba-e673816e691f) ([Notes](https://github.com/jreades/i2p/blob/master/lectures/8.2-Linki
ng_Spatial_Data.md))
- Watch: [Grouping Data](https://web.microsoftstream.com/video/7f8df345-7339-466c-be60-a6
5be1ad6b57) ([Notes](https://github.com/jreades/i2p/blob/master/lectures/8.3-Grouping_Dat
a.md))
- Watch: [Data Visualisation](https://web.microsoftstream.com/video/4cc8c5a2-5881-4342-ad
da-32b39a989d90) ([Notes](https://github.com/jreades/i2p/blob/master/lectures/8.4-Visuali
sing_Data.md))

#### Readings

- [@dignazio:2020, chap. 3] On Rational, Scientific, Objective Viewpoints from Mythical,
Imaginary, Impossible Standpoints in Data Feminism; [Pre-review URL](https://bookbook.pub
pub.org/pub/8tjbs2x5)
- [@badger:2019] The Neighborhood Is Mostly Black. The Home Buyers Are Mostly White. [URL
](https://www.nytimes.com/interactive/2019/04/27/upshot/diversity-housing-maps-raleigh-ge
ntrification.html)

#### Contribution

- Padlet: [Collaborative Agenda]

#### Quiz!

- Complete the [short Moodle quiz](https://moodle.ucl.ac.uk/mod/quiz/view.php?id=2579101)
 associated with this week's activities.

### Workshop

- Reviewing the **Collaborative Agenda**
- Discussion of **Readings**
- **Live Coding**

### Practical

The practical can then be downloaded from GitHub.
