---
author: "Jon Reades"
email: "j.reades@ucl.ac.uk"
title: "Assessments"
other: ""
date-as-string: "1st October 2025"
format: revealjs
---

## The Assessments

1. Open-Book Exam ({{< var assess.quiz-weight >}})
2. Group Work
   - Content ({{< var assess.group-writing-weight >}})
   - Code ({{< var assess.group-code-weight >}})
3. Peer Evaluation ({{< var assess.peer-weight >}})

# Assessment #1

---

### What is it?

Timed, Open Book Exam

- Timed: once you start the assessment you will have a fixed amount of time in which to complete it; **1h 20m** for most students, but students with relevant SORAs have **2 hours** (please email me).
- Open Book: **You may *look*** at any resource you like, **you may not *ask*** another human being for assistance. **You *may* use ChatGPT or another LLM** but must report when you do.

---

### When is it?

- **{{< var assess.quiz-date >}}** from either **{{< var assess.quiz-time >}}**^[This is the 'window' for doing the assessment. You can start any time *after* the window opens but must finish *before* the window closes.]

### Where is it?

- You will access your questions **through Moodle**. You can write the code that you need to *answer* the question in JupyterLab or any other **Python programming environment**. 

### What is covered?

- Any concept *up to and including Week 5* is 'fair game'. The exam will consist of *no more* than 10 questions.^[So, roughly, that means about 12 minutes/question.] 

---

### How is it graded?

- We will manually grade it in Moodle. There are roughly 960 answers so we may make some mistakes and you can flag these where it is clear this has happened.

### Why should I report ChatGPT?

- The use of ChatGPT has no impact on your grade, we are primarily curious about how useful people are finding it and whether LLMs affect your understanding.

# Assessment #2

## Overview

The reproducible analysis and briefing will be developed as part of a group and has two components:

1. The **content** ({{< var assess.group-writing-weight >}}, submitted as a PDF file): how do the answers written by the group engage with the set questions through a mix of literature, critical thinking, and data analysis?
2. The **code** ({{< var assess.group-code-weight >}}, submitted as a QMD file): how well does the group's code transfer to a 'clean' environment on a different computer?

These are submitted *separately* to two separate submission areas. Only one person needs to submit on behalf of the group. 

## In-Class Feedback

Because the format is novel, and also entails using Quarto, starting in Week 7, groups will be randomly selected to present their (draft) answer to that week's question *in class*. 

- Formative feedback will be provided *in class* on the quality of the response.
- If the selected group has not prepared an answer then no formative feedback will be provided for that question.

This is intended to ensure that: a) you are doing the thinking and reading to progress towards submission; and b) you are learning how to use Quarto.

## Resources

- A [template]({{< var module.web >}}/assessments/Group_Work.qmd) has been provided. By default it generates *both* [PDF]({{< var module.web >}}assessments/Group_Work.pdf) and [HTML]({{< var module.web >}}/assessments/Group_Work.html) output, but please *only* submit the PDF
- A [reproducibility rubric](../assessments/code.qmd) explaining our expectations in greater detail.
- A [briefing rubric](../assessments/content.qmd) explaining our expectations in greater detail.

# Assessment #3

## Overview

We know that people contribute differently to groups or, sometimes, not at all. This self- and peer-assessment seeks to quantify that contribution while also prompting you to reflect on what *you* contributed to your group and the wider dynamics of working as part of a team.

- You will self-assess your own contribution to the group through a brief narrative.
- You will *then* score everyone else's self-assessment and provide short feedback. 

This assessment should not take more than 30 minutes *in total*, but it has to be done in two parts.

---

### When is it due?

- Part 1: {{< var assess.peer1-date >}} @ {{< var assess.peer1-time >}}
- Part 2: {{< var assess.peer2-date >}} @ {{< var assess.peer2-time >}}

### Where do I access it?

- You will use UCL's IPAC tool [accessed through Moodle](https://moodle.ucl.ac.uk/course/view.php?id=54436#).

### How does it work?

- Complete a self-evaluation *first*.^[Yes, it's due several days before the final submission because you *should* be working on it during term time!]
- Come back *after* the group submission to complete the peer-evaluation.^[This should take about 20-30 minutes *max*.]

## Time to Organise!

You are aiming for a group of four:

- If you are in a group of less than four you *may* be partnered with students in another practical session to make a 'full strength' group of up to five. 
- In this case, you can ask to be reallocated to a mutually convenient practical session so that you are not penalised by being unable to work together.
- I would encourage you to start sitting and working together, and for *one* of you to set up and share a private GitHub repo for Assessment #2 (more on this in a second).

And **remember**: *talk* about how you want your group to work! See: [Group Working](../sessions/week4.html#in-person-lectures) talk.^[*Note*: In my experience overly narrow specialisation does not work.]

# Questions? {background-image="/img/web/title-slide.png" background-color="#f7eff5" background-opacity="0.2"}

<h3>References</h3>
