---
author: "Jon Reades"
email: "j.reades@ucl.ac.uk"
title: "Responding to Feedback"
other: ""
date-as-string: "10th November 2025"
format: revealjs
---

```{python}
#| echo: false
import pandas as pd
df = pd.read_excel('Continuous Module Feedback (Checkpoint 1)(1-66).xlsx')
```

# We take it seriously!

We are not perfect and we are always looking to improve. Thank you to the 66 people who took the time to comment on one mor more points!

## Important Qualification 1

CASA does not get to pick the rooms in which these classes are taught! And we barely have any control at all over timings^[Fun fact: we have been offered practicals *before* lectures on occasion.].

## Important Qualification 2

You might see your comments here. We are not trying to embarrass anyone. We are trying to improve the course.

## The Good

In general, you seem to know what we're banging on about:

```{python}
#| output: asis
#| echo: false

for i in range(6,10):
    pct = df.iloc[:,i].isin(['Agree','Strongly Agree']).sum() / df.shape[0]
    print(f"- {(pct*100):.0f}% of you agreed or strongly agreed that '{df.columns.to_list()[i]}'")
```

We will need to see how this changes from Week 6...

## Free Text

I paraphrase^[I would always welcome more detail!]:

- Some concerns that technical component is scaling up quickly, that Code Camp is not enough
- One comment about feeling overwhelmed by resources.
- One comment about links between pre-recorded lectures, in-class discussion, and practicals. Felt it would be helpful to have questions about the pre-recorded lecture content.
- One comment for greater participation/debate in the 'lecture'.

## Start

The following requests for new activities were made:

- Review the practical / Links to real-world problems.
- More 'worked examples' / Live coding.
- More (group) discussion of readings^[Including calling on people *without* their hand raised.] / More coding.
- Less ethics / More ethics.
- Make the practicals a group effort.

## Stop

- Practicals are intimidating as many seem very advanced already.
- Emphasise the coding more than theory.
- One 'voice' at front of room in the practicals.
- Nothing!

## Continue

- Check on GitHub and repo setups
- "Continue with making the subject approachable, and understanding as you are. Makes coding less intimidating."
- "The reading discussions in the start of class are a good way to engage with the reading list. The amount of resources provided each week to engage with out of course learning is also great."^[Several variations of this.]
- More CASA-examples.
- Trying to encourage student engagement.

## Common Threads?

Student feedback is often bimodal^[This seems the commonality across years!]:

- Some students want more technical content. Some find the technical content we have too much.
- Some students want more discussion. Some find the discussion we have too much.

## My Challenge to You

- If you think the live session is just a recap of the readings, why aren't you chiming in with *your* thoughts? 
- If you think that the discussion should 'go deeper', why aren't you asking deeper questions?
- If you think that Git and Podman/Docker aren't part of *doing* data science, why aren't you pushing us to explain it better?
- ~~If you are struggling with the practical examples, why aren't you asking for more examples?~~

# One Thought?

It *seems* to me that the positive comments are from students who are seeing 'the bigger picture' in terms of how the readings, lectures, and practicals fit together. It's not 'technical' *or* 'discussion' (or ethics or theory) but 'technical' *and* 'discussion'. 

::: {.notes}

The technical aspects will expose you to the ethical and other problems academics are writing about in an applied setting. The discussions will help you understand the technical aspects in a broader context. Together, they will make you a *better* data scientist.

:::

## My Current Takeaways (Last Year)

Last year, I was looking at:

1. Resequencing lectures in weeks 1–3 to try to introduce fewer tools at once. 
2. Revisiting weeks 1–5 to see where practicals can be anchored in examples and possibly even introduce a very small version of the InsideAirbnb data set (instead of the city pseudo-data).
3. Developing additional materials for those who want to go deeper.
4. Reviewing signposting in lectures and practicals.

## My Current Takeaways (This Year)

Pending additional feedback from *you*, I am looking at:

1. Reviewing more 'real world' examples (more of what's *already* in the pre-recorded lectures?).
2. Reiterating links between practicals, examples, and pre-recorded lectures.
3. Striking a balance between 'on the spot' and 'opt-in' discussion.

I will struggle to do: live-coding *and* discussion *and* recapping *and* signposting in 2 hours... 

# Questions? {background-image="/img/web/title-slide.png" background-color="#f7eff5" background-opacity="0.2"}
