---
author: "Jon Reades"
email: "j.reades@ucl.ac.uk"
title: "Responding to Feedback"
other: ""
date-as-string: "1st October 2025"
format: revealjs
---

# We take it seriously!

We are not perfect and we are always looking to improve.

## Important Qualification 1

CASA does not get to pick the rooms in which these classes are taught! And we barely have any control at all over timings^[Fun fact: we have been offered practicals *before* lectures on occasion.].

## Important Qualification 2

You might see your comments here. We are not trying to embarrass anyone. We are trying to improve the course.

## The Good

I paraphrase:

- Activities, reading, and exam relate and the lectures have some fun examples that are easy to follow.
- There is some reading, followed by questions which makes students engage with the homework.
- Practicals are interactive, with clear tutorials explaining the topic step by step.
- A lot of materials for further learning and organized so that I could practice a lot by myself.
- Really strong PGTAs.

## The Bad (and the Ugly) 1

I paraphrase:

- Too much ethics in FSDS so I didn't have time to practice my coding skills.
- I think it’s not necessary to spend too much time discussing reading materials at class. Instead, we can ask some questions on Slack after class.
- Lectures are focused on summarizing the videos and the readings. I would get much more out of them if they were more discussion-based, and we could discuss the readings on a deeper level.
- The discussion in the lecture is just a very low-level recap of the readings... For those of us that have read and understood the readings, we don't learn much from the questions being discussed. We could be spending that time on technical elements instead.

## The Bad (and the Ugly) 2

I paraphrase:

- The technical content is very slow and we don't write a lot of code in the practicals, so I feel like I'm not learning and remembering it very well. 
- I've tried my best to review and catch up but I don’t know why I still struggle a lot figuring the whole picture. Suddenly the script went from simple into complex really quick.
- I’m quite confused about the content of practicals 1-5. Maybe combining the real data analysis with detailed data learning (objects, function) is better to understand.
- Too much emphasis on Git, Podman/Docker, etc. 
- There was a lot of information about different concepts (Git, Jupyter, Podman/Docker, Python) and it was very overwhelming.

## Common Threads?

Student feedback is often bimodal and motivated by frustration:

- Some students want more technical content. Some find the technical content we have too much.
- Some students want more discussion. Some find the discussion we have too much.

## My Challenge to You

- If you think the live session is just a recap of the readings, why aren't you chiming in with *your* thoughts? 
- If you think that the discussion should 'go deeper', why aren't you asking deeper questions?
- If you think that Git and Podman/Docker aren't part of *doing* data science, why aren't you pushing us to explain it better?
- If you are struggling with the practical examples, why aren't you asking for more examples?

# One Thought?

It *seems* to me that the positive comments are from students who are seeing 'the bigger picture' in terms of how the readings, lectures, and practicals fit together. It's not 'technical' *or* 'discussion' (or ethics or theory) but 'technical' *and* 'discussion'. 

::: {.notes}

The technical aspects will expose you to the ethical and other problems academics are writing about in an applied setting. The discussions will help you understand the technical aspects in a broader context. Together, they will make you a *better* data scientist.

:::

## My Current Takeaways

Pending additional feedback from *you*, I am looking at:

1. Resequencing lectures in weeks 1–3 to try to introduce fewer tools at once. 
2. Having a chat with Andy to ensure we align Git content and develop understanding across *both* modules.
3. Revisiting weeks 1–5 to see where practicals can be anchored in examples and possibly even introduce a very small version of the InsideAirbnb data set (instead of the city pseudo-data).
4. Developing additional materials for those who want to go deeper.
5. Reviewing signposting in lectures and practicals.

# Questions? {background-image="/img/web/title-slide.png" background-color="#0F0C11" background-opacity="0.2"}
