
In the midst of an election, a newspaper has broken the story of an advisor on social mobility to the Mayor owning three homes, two of which are let on Airbnb (one of which is still council-owned housing!). The opposition has announced a plan to force all *professional landlords* to register their properties and face higher Council Tax rates claiming that Airbnb is 'out of control' in the capital. 

The Mayor wants to understand the scale of the ‘problem’ and the likely impacts of the opposition's proposal so that they can either adopt it (and show how responsive they are) or demonstrate how poorly thought-through the opposition’s proposal is (and show that they’re not ready to govern). 

They have come to you---their team of data analysts and policy advisors---for a briefing supported by evidence and visualisations that they can use in their campaign communications. You are working in an information-poor environment, so you will need to make assumptions, justify them clearly, and show how they affect your conclusions. Use data, reasoning, and clear visualisation to build a persuasive and evidence-informed argument.

### 1. Is Airbnb 'out of control' in London?

::: {.duedate}

Draft answer due Week 7.

:::
 
### 2. How many professional landlords are there?

::: {.duedate}

Draft answer due Week 8.

:::
 
### 3. How many properties would be affected by the opposition’s proposal?

::: {.duedate}

Draft answer due Week 9.

:::
 
### 4. What are the likely pros and cons of the opposition’s proposal (for the Mayor, for residents, and for the city)?

### 5. Can the story be reframed as a positive one about social mobility or housing opportunity?
