---
title: "Data Audit (30%)"
---

This individual assessment is due {{< var assess.bio >}} (after Reading Week). The data set for which the 'biography' will be written is the [Inside Airbnb data for London](https://github.com/jreades/i2p/raw/master/data/src/2020-08-24-listings.csv.gz). This assessment will be quite straightforward if you have been doing the readings and keeping up with the basics of using Markdown, and rather challenging if you have not.

This assessment is, in part, a technical 'test run' for the policy report: you will not fail *this* assessment if you decide to write it in Word or some other editor, but now is a good time to check that you understand how Quarto works before beginning work on the other two assessments or on your dissertation!

## Format

This is a structured assessment that requires you to answer the following questions:

1. Who collected the data? *2 points; 25 words; Consider the source of the data and its relation to the underlying data generating process.*
2. Why did they collect it? *4 points; 50 words; Consider the purposes for which the data was collected and how this might shape its structure or content.*
3. How was it collected?  *7 points; 75 words; What was the method by which the data was collected and how might this shape its structure, content, or completeness.*
4. What useful information does it contain? *12 points; 100 words; Discuss how the data might support a range of analyses and note any limitations encountered so far in class or in your own investigations.*
5. To what extent is the data 'complete'? *25 points; 200 words; Reflecting on your earlier answers, and drawing on what you've learned about the data so far in class, to what extent is this data a 'complete' picture of Airbnb's operations in London?*
6. What kinds of analysis would this support? *15 points; 200 words; Given the issues identified above, what **kinds** of analysis would this data support? You do not need to propose a specific analysis and should instead focus on generic **classes** of analysis.*
7. Which of the analyses outlined above are ethical? *35 points; 350 words; Discuss the ethics of these classes of analysis with reference to your earlier answers and to the assigned readings.*

## Restrictions

The word limit for this assessment is **1,050 words**. The per-question word counts above are indicative and are not a 'hard' limit. 

Tables should be added in an appendix and do not count towards the word total.

Do not use figures.

Any works references should appear in a *Bibliography*.

## Referencing

You will need to reference various documents as part of this submission. It is possible to write these 'by hand', but you might find it helpful to also learn about BibTeX fies and Markdown referencing in Quarto. The Docker image that we have provided has Quarto pre-installed, but because of the complexities of specifying fonts in Docker you are likely to find it easier to install it natively [for your Operating System](https://quarto.org/docs/get-started/). 

You'll also need [BibDesk](https://bibdesk.sourceforge.io) (Mac) or [JabRef](https://www.jabref.org) (Mac/Windows) or similar (Zotero shuould also work) to edit the BibTeX file (outside of Docker).

## The Template

Once you have installed Quarto, you will need the following files:

1. The template file (`.qmd`) that we have provided: [Data_Biography.qmd](https://github.com/jreades/fsds/blob/master/assessments/Data_Biography.qmd).
2. The CSL file (`.csl`) that governs how references are done: [harvard-cite-them-right.csl](https://github.com/jreades/fsds/blob/master/assessments/harvard-cite-them-right.csl).
3. The BibTeX file (`.bib`) that will contain any references you use: [bio.bib](https://github.com/jreades/fsds/blob/master/assessments/bio.bib) 

:::{.callout-note}
## Really Look at the Template!

You'll notice that the template specifies three fonts (`mainfont`, `monofont`, `sansfont`). If you don't have these fonts installed on your computer then `quarto render...` will fail. These are installed in Docker, and I've added links in the template to show how you can download them for your own computer.

You are welcome to change the fonts to something already installed on your computer (this will help you to learn about font-management), or you can follow the links embedded in the template to download the specified fonts and install them for your computer.
:::


## Rendering

These three files together will enable you to 'render' the [Markdown template](https://github.com/jreades/fsds/blob/master/assessments/Data_Biography.qmd) as a PDF for submission. To do this, ensure that all three files above are in the *same* folder (e.g. `~/git/fsds/bio`), in which case you'd see *something* like:

```bash
cd ~/git/fsds/bio
ls . # Should show a .qmd file, a .csl file, and a .bib file
quarto render Data_Biography.qmd
```

This should render the PDF with a look something like [this example output](./Data_Biography.pdf).
