# Policy Briefing {.unnumbered}

The *Policy Briefing* will present an analysis of data from the [Inside Airbnb web site for London](http://insideairbnb.com/get-the-data.html). Students may use data from more than one time period if they wish, but this is not required. The briefing will be written ***as if* to update** the Mayor of the Greater London Authority on the challenges/opportunities relating to Airbnb's operations in London. As such, the *Policy Briefing* will begin with a short Summary, including *Key Findings* and, if desired, *Recommendations*; this will be followed by a brief **review of the evidence** from both London and elsewhere, and then an analysis supported by the data and presented using appropriately generated and selected **tables**, **charts**, and **maps**.

The briefing *may* be written *without* substantially new modelling or coding by drawing on the code written in practicals to develop an analysis based on the judicious use of descriptive statistics (see, for instance, [Housing and Inequality in London](https://www.centreforlondon.org/publication/housing-and-inequality-in-london/) and [The suburbanisation of poverty in British cities, 2004-16: extent, processes and nature](https://www.tandfonline.com/doi/full/10.1080/02723638.2017.1405689)), but it is likely that a *better* mark will be obtained by demonstrating the capacity to go beyond exactly what was taught by selectively deploying more advanced programming techniques. 

## Format

This is _not_ an essay, and students who submit a traditional essay format will have 10 points deducted from the overall mark (i.e. if your original mark was 70 then we deduct 10 to make your final mark for this assessment a 60). Examples of the kind of format, tone, and content expected are provided below and there will be opportunities to discuss the submission during Term. You should refer to the [models](./models.qmd) provided for insight into how to organise the briefing and how to write for a target audience.

::: {.callout-warning}
## Write for Your Audience

Always remember that you are writing this briefing *for the Mayor of London*! Are they going to know what *k*-Means Clustering is? Will they *care*? 

What makes writing a good briefing *hard*---and not just about writing good code---is finding the right balance of technical detail and high-level explanation: you can't just say 'here are the five types of accommodation we found...', but you *also* can't say 'we tested clustering solutions in the range 3--50 and found the optimal result at `k=12`...' You should have a look at the [examples](./models.qmd).
:::

## Word Count

The word limit for this group piece is **2,500 words**.

## Preparing Your Submission

You are expected to use Markdown+Quarto for this submission and 10 points will be deducted if you do not do so down to a minimum of 50 (i.e. if your original mark was 70 then we would deduct 10 to make your final mark for this assessment a 60, but if your original mark was 55 then we would only deduct 5 points). You may be asked to provide evidence that Markdown was used to generate your submission. You are free use the [Data Biography Template](https://github.com/jreades/fsds/blob/master/assessments/Data_Biography.qmd) as a starting point if you wish, but should probably look at the [Quarto Guide](https://quarto.org/docs/guide/) and, in particular, the [PDF options](https://quarto.org/docs/output-formats/pdf-basics.html).

You must write your submission in Markdown and maintain a copy of the submission in GitHub. It is not necessary that your submission be fully GitHub Markdown-compatible (i.e. you can use another rendering engine such as Quarto) but edits must be tracked in GitHub so that we can review contributions if necessary.
