---
title: "Content"
nocite: |
  @Travers:2016, @Wachsmuth:2018b, @Bivens:2019 
---

The *Content* is worth {{< var assess.group-writing-weight >}} of your module mark. You will be writing **for a non-technical audience**: the incumbent Mayor has asked you to rapidly respond to a political scandal and a proposal for regulation by the opposition candidate.

The responses to the set questions *may* be written *without* substantially new modelling or coding through the judicious use of descriptive statistics (see, for instance, [Housing and Inequality in London](https://www.centreforlondon.org/publication/housing-and-inequality-in-london/) and [The suburbanisation of poverty in British cities, 2004-16: extent, processes and nature](https://www.tandfonline.com/doi/full/10.1080/02723638.2017.1405689)). 

Students may use data from more than one time period if they wish, but this is not required. You can see the available data sets [on Orca](https://orca.casa.ucl.ac.uk/~jreades/data/). 

## Set Questions

{{< include _questions.qmd >}}

## Style

This is _not_ an essay, and students who submit answers using a traditional essay style will see their overall mark impacted as a result. You must preserve the question/response format, and your responses should be readily-grasped by an intelligent, but non-technical audience. This doesn't mean that you don't need citations, but you should not employ an academic writing style. See the [models](#models) provided below for insights into how to write for a less technical audience.

There will also be opportunities to discuss the submission during the second half of term. 

::: {.callout-warning}

## Write for Your Audience

What makes writing a good briefing *hard*---and not just about writing good code---is finding the right balance of technical detail and high-level explanation: you can't just say 'here are the five types of accommodation we found...', but you *also* can't say 'we tested clustering solutions in the range 3--50 and found the optimal result at `k=12`...' You should have a look at the [examples](#models).

:::

## Word Counts & Figures

### Word Counts

Each figure or table **counts for 150 words**, and so students should give careful consideration to the trade-offs involved: more figures may serve to illustrate your points but leave you with much less space to synthesise and present and argument.

The overall word limit for this assessment is **2,500 words**.

### Figures & Tables

Unless you are presenting (and citing) a figure from another source as part of your framing, all figures and tables used **must be generated by Python code cells** included in the markdown file. You may not modify or create figures in another application since this undermines the reproducibility of the analysis.

### A/B Figures

A figure **with A/B/C elements** will count as one figure, but only where the parts parts are conceptually related (e.g. before/after; non-spatial/spatial distribution; type 1 and type 2; etc.). The output from PySAL's LISA analysis library, for instance, is pre-formatted as 3 figures. Seaborn's `jointplot` will only be considered to be *one* plot even though it is *technically* three because the distribution plots in the margin are related to the scatter plot that is the focus of the plot.

**In principle**, a briefing with 16 figures would have no space for any text or interpretation; this choice is deliberate because its purpose is to focus your attention on which charts and tables *best*-communicate your findings. **In practice**, using A/B/C figure layouts then you are looking at up to 48 separate figures before hitting the limit, though you would at this point be producing an infographic and not a briefing.

## Assumptions

It is highly likely that you will need to make substantial use of *assumptions* in developing your briefing for the Mayor. These should be plausible and, where possible, documented. For example: 

> Based on <some author> (2021), we assume that the average visitor to London walks at a rate of 3m/s (180m/minute). We further assume that a 10-minute walk is reasonable, giving us a limit of 1,800m...

Or:

> We assume that tourists spend approximately £X/day in their local area (see, e.g., <some author>, 2016), implying that each property generates a maximum of £Y/year in local spending (assuming continuous occupation). In practice, we adopt the approach of XXX (2019) to estimate occupancy from reviews to generate a more realistic impact of...

So you can see that neither of these requires more than a couple of citations to allow you to estimate some reasonable threshold for a metric of interest. This will be a lot simpler than trying to look up global tourist spending information or TfL travel stats. Yes, it's a rough-and-ready estimate, but it also doesn't pull the number out of thin air.

<!-- 
- A [marking rubric](./Group_Rubric.pdf) is available.
- A [proposal outline](https://github.com/jreades/fsds/blob/master/assessments/Project_Outline.qmd) template is available (see: [example](Project_Outline.pdf)).
-->


## Referencing

You will need to make use of BibTeX and Markdown referencing in Quarto. 'Hard-coded' references will not be considered.

::: {.callout-tip}
## Referencing in Quarto 

Although you can create BibTeX entries by hand, you will probaly want to make use of [BibDesk](https://bibdesk.sourceforge.io) (Mac) or [JabRef](https://www.jabref.org) (Mac/Windows). Zotero shuould also work to edit the BibTeX file.

In Google Scholar, if you want to add a reference to your BibTeX file there's an option in the `Cite` functionality to copy a BibTeX entry to the clipboard and then pasted this into BibDesk or JabRef.

:::

## Models

Although the following examples are all much longer than permitted under the assessment format, they are exemplary in their communication of the data and key findings in a manner that is clear, straightforward, and well-illustrated using maps, charts, and tables. So while they wouldn't work for a busy Mayor *per se*, they can still help you to think about how best to present information for non-expert audiences:

1. Travers et al. (2016), *Housing and Inequality in London*, Centre for London; [URL](https://www.centreforlondon.org/publication/housing-and-inequality-in-london/).
2. Bivens, J. (2019), *The economic costs and benefits of Airbnb*, Economic Policy Institute; [URL](https://www.epi.org/publication/the-economic-costs-and-benefits-of-airbnb-no-reason-for-local-policymakers-to-let-airbnb-bypass-tax-or-regulatory-obligations/).
3. Wachsmuth et al. (2018), *The High Cost of Short-Term Rentals in New York City*, Urban Politics and Governance research group, McGill University; [URL](https://www.mcgill.ca/newsroom/files/newsroom/channels/attach/airbnb-report.pdf).

::: {.callout-tip}

### Longer Questions

Notice how these 'models' differ from a traditional essay format. So instead of *Introduction*, *Literature*, etc. you will see the evidence is developed in parallel with the background material. This format provides for more flexibility in style and presentation, though you will note that they all refer to a mix of academic and grey literature as well!

:::

## Partial Bibliography

You will also want to expand on the partial bibliography shown in the [Templates](./resources.qmd) section. This is by means complete and you will likely find other relevant work 'out there', but this gives you a good starting point. 

<!-- 
- A [marking rubric](./Group_Rubric.pdf) is available.
- A [proposal outline](https://github.com/jreades/fsds/blob/master/assessments/Project_Outline.qmd) template is available (see: [example](Project_Outline.pdf)).
-->
