---
title: "Timed Open Book Exam"
---

This 'exam' (to be completed on {{< var assess.quiz-date >}} between {{< var assess.quiz-time >}} and worth {{< var assess.quiz-weight >}}) will be administered as a quiz through Moodle: you will be asked to download a small data set and perform a series of specified analytical tasks using that data. For each question you will be asked *both* to type in an answer *as a comment* (which may be numerical or textual) and to paste in the code that you have used to obtain that answer.  

For the exam itself you have 2 hours (3 hours with a relevant SORA) to *do* the coding and submit your answers. The 'clock' starts on the first question and finishes either after 2 hours (3 hours with a relevant SORA) or at the end of the window period ({{< var assess.quiz-time >}}) **whichever comes first**. So *all* incomplete exams are closed at the end of the window: if you have a SORA you should plan to start the exam one hour earlier so as to have the maximum amount of time.

## Expectations

This is the first year that we have attempted to run a timed, open-book examination as part of this module so we may make adjustments to the process based on the capabilities of the class (taken in the round) and the challenges presented by the data set selected. 

However, as a general set of expectations:

- Any content covered prior to Reading Week may be encountered in the exam (so we will only test you as far as the use of `pandas` with numeric data)
- The *principal* library upon which the exam will rely is `pandas`.
- The exam is 'open book', but there are *three* important limitations: 
  1. You may not obtain direct assisstance from another person (either in-person or online); 
  2. You may not *ask* questions relating to the exam on StackOverflow or other 'online help boards'. 
  3. You *may* use ChatGPT or another LLM. 
- *However*, if you make use of an external resource (e.g. you search for and find relevant code on StackOverflow or use ChatGPT) you *must* acknowledge this using the form set out below.
- Anyone found to have cheated on this submission will receive a mark of `0` and the resit assessment will involve producing an analysis in a timed context under direct supervision of module staff: you will be **required** to be present *in-person* for the resit (this is likely to be during the summer period) and will have to complete a set of coding tasks specified by the module leader.

In other words: don't do it.

## Format

The format of the answer to each question should be of the form:

{{< include _exam_template.qmd >}}

So, for example, your answer to the question 'To two decimal places, what is the modal price and number of nights in the data set?' *might* look something like this:

{{< include _exam_example.qmd >}}

Good luck!
