---
title: "Context"
---

The overall assessment package is intended to test students' comprehension of, and ability to integrate, technical skills with a broader understanding of, and reflection upon, computational approaches to urban research and spatial data science. 

## Assessment Elements

The assessments are grounded in a mixture of critical reflection and group work that map on to real-world data science challenges, including:

1. [Timed Open Book Examination](./exam.qmd) ({{< var assess.quiz-weight >}}) to ensure that you are acquiring the fundamentals of data analysis in Python, and simulate the real-world challenge of having to write code to a deadline (due {{< var assess.quiz-date >}});
2. [Collaboratively evaluating and analysing a data set](./group.qmd) ({{< var assess.group-weight >}}) as a group you will be determining the suitability of a data set for tackling an analytical 'problem' using a mix of coding, analysis, *and* presentation skills in a reproducible format {{< var assess.group-date >}});
3. [Reflecting on the process](./individual.qmd) ({{< var assess.peer-weight >}}) to better-understand *why* a project succeeded/failed so as to improve future outcomes and recognise the contributions of individual members of the group to the success of the project (due {{< var assess.peer-date >}}).

## Rationale

Collectively, these assessments seek to provide multiple opportunities to 'shine' both individually and as part of a group. You do *not* need to be the best programmer in the class in order to do well on these assessments. Indeed, focussing only on the programming is likely to result in a *low* mark because it missed the **context** in which data science and data analysis 'work'. As a budding data scientist/analyst your job is just as much to understand your audience and their needs: you will work with clients who can't really articulate what they want or why, so good project management often involves putting yourself in your client's shoes and working out how to translate what they *say they want* into what they *actually need*.

You will therefore do poorly on the assessments if you do not do the readings, watch the pre-recorded lectures, or participate in discussions (both online and in-person during practicals and classes). These provide you with **context** for the work that is being done when you start typing and running code in a Jupyter Notebook. Code is the *how*. Context is the *why*.
