# Individual Reflection (20%)

This individual assessment due {{< var assess.individual >}} asks you to reflect *on the process* of 'doing data science' as part of a team, since this format is typical of real-world projects. Many companies (e.g. Apple, Google, etc.) employ an Agile project format in which teams undertake a 'Retrospective' at the end of a project in order to identify ways to improve how they work in the future. We are *not* asking you to do this as a group (indeed, it's an *individual* reflection), but we hope that this will help you to develop as a budding analyst or data scientist.

### Format

You must answer these 3 questions:

1. What factors do you think help to explain what went well/not well in the project? *3 points; 200 words; Critically engaging with challenges faced by the group will **not** result in a low mark.*
2. How do you think the other students in *your* group would evaluate *your* contribution to each of these outcomes? *12 points; 400 words; Honesty is the best policy here as we may compare your response with that of the rest of the group.*
3. Briefly describe *one* event or experience from the group assessment that gave you new insight into 'doing' data science, and explain how and why this will be useful to you in the future. *10 points; 400 words; Try to connect this to either/both of employability and transferrable skills.*

### Word Limit

The word limit for this assessment is **1,000 words**.

### Preparing Your Submission

You are free use the [Individual Reflection Template](https://github.com/jreades/fsds/blob/master/assessments/Individual_Reflection.qmd) as a starting point, but you may also wish to experiment with other templates, styles, or fonts. References are not required unless you wish to connect your reflection to specific publications. Note the requirement to include a 'Sustainable Authorship' section.

### Marking 'Rubric'

The following factors will be taken into account as part of your overall mark:

- Making use of sustainable authorship tools (you *must* specify these in the **Sustainable Authorship Tools** section!) to generate the submission; considerations include: sustainable authorship tools employed (e.g. Markdown, LaTeX, free fonts, etc.); citation/referencing where used; design/layout.
- Reflection on factors impacting success/lack of success in project outcomes; considerations include: demonstration of critical thought; ability to generalise from specific cases; identification of causal factors.
- Understanding of group dynamics; considerations include: empathy/understanding displayed; awarness of extrinsic/intrisic motivations.
- Reflection on skills acquired: clear identification and articulation of relevance (or not) of skills acquired; ability to present both failures and successes in constructively critical light; understanding of skills needed across broadly-construed 'data science' team (this does *not* have to be about coding!).
