---
title: "Assessment #3: Individual Reflection Marking Rubric"
author: "Jon Reades"
date: "9/9/2022"
toc: false
number-sections: true
colorlinks: true
format:
  pdf:
    include-in-header:
      text: |
        \addtokomafont{disposition}{\rmfamily}
        \KOMAoption{fontsize}{11pt}
    #documentclass: report
    mainfont: "Spectral"
    papersize: a4
    geometry:
      - top=25mm
      - left=40mm
      - right=30mm
      - bottom=25mm
      - heightrounded
---

## Key Facts

- Deadline: {{< var assess.individual >}}
- Weighting: 20% of module grade.
- Format: PDF submitted to Moodle. See [online guidance](https://jreades.github.io/fsds/assessments/individual.html) for details.

## Marking

The following factors will be taken into account as part of your overall mark:

- Making use of sustainable authorship tools (you *must* specify these in a **Sustainable Authorship Tools** section!) to generate the submission; considerations include: sustainable authorship tools employed (e.g. Markdown, LaTeX, free fonts, etc.); citation/referencing where used; design/layout.
- Reflection on factors impacting success/lack of success in project outcomes; considerations include: demonstration of critical thought; ability to generalise from specific cases; identification of causal factors.
- Understanding of group dynamics; considerations include, but are not restricted to, empathy/understanding displayed and awarness of extrinsic/intrisic motivations.
- Reflection on skills acquired: clear identification and articulation of relevance (*or* not) of skills acquired; ability to present both failures and successes in constructively critical light; understanding of skills needed across broadly-construed 'data science' team (this does *not* have to be about coding!).

Marks will be assigned using the following scale:

- **Weak**: Little or no individual reflection; answer shows little or no critical self-awareness or reflection upon the dynamics of group work . The student has failed to connect any of this experience to wider, post-graduate professional concerns.
- **Fair**: A sound individual reflection; answer demonstrates a basic level of critical self-awareness and reflection upon the dynamics of group work. The student has made basic connections between this experience and wider, post-graduate professional concerns. 
- **Excellent**: An outstanding individual reflection; answer engages both critically and reflexively with the interplay of individual and group dynamics. The student has clearly drawn relevant insights from the experience that could be applied in a wider, post-graduate context.

|   | Question | Points | Word Count | Weak | Fair | Excellent |
|:--|:--------------------------|---:|------:|----:|----:|------:|
| 1 | What factors do you think help to explain what went well/not well in the project? | 3 | 200 | 0-1 | 2-3 | N/A |
| 2 | How do you think the other students in *your* group would evaluate *your* contribution to each of these outcomes? | 10 | 400 | 0-3 | 4-7 | 8-10 |
| 3 | Briefly describe *one* event or experience from the group assessment that gave you new insight into 'doing' data science, and explain how and why this will be useful to you in the future. | 10 | 400 | 0-3 | 4-7 | 8-10 |
| 4 | Does the submission make appropriate use of Sustainable Authorship approaches and tools? | 2 | N/A | 0 | 1 | 2 |

*Note*: the word counts provided are indicative.
