## Models and Topics

## Models for the Policy Briefing

Although the following examples are all much longer than permitted under the assessment format, they are exemplary in their communication of the data and key findings in a manner that is clear, straightforward, and well-illustrated:

::: {.callout-tip}
Notice how the format of these is *broadly* similar but differs from a traditional essay format. So instead of *Introduction*, *Literature*, etc. you will see *Key Findings*, potentially some *Recommendations*, and two or more sections or chapters in which the evidence is developed in parallel with the background material. This format provides for more flexibility in style and presentation, though you will note that they all refer to a mix of academic and grey literature as well!
:::

1. Smith, D.A. (2010), *Valuing housing and green spaces: Understanding local amenities, the built environment and house prices in London*, GLA Economics; [URL](https://www.london.gov.uk/sites/default/files/gla_migrate_files_destination/GLAE-wp-42.pdf).
2. Travers, T. Sims, S. and Bosetti, N. (2016), *Housing and Inequality in London*, Centre for London; [URL](https://www.centreforlondon.org/publication/housing-and-inequality-in-london/).
3. Bivens, J. (2019), *The economic costs and benefits of Airbnb*, Economic Policy Institute; [URL](https://www.epi.org/publication/the-economic-costs-and-benefits-of-airbnb-no-reason-for-local-policymakers-to-let-airbnb-bypass-tax-or-regulatory-obligations/).
4. Wachsmuth, D., Chaney, D., Kerrigan, D. Shillolo, A. and Basalaev-Binder, R. (2018), *The High Cost of Short-Term Rentals in New York City*, Urban Politics and Governance research group, McGill University; [URL](https://www.mcgill.ca/newsroom/files/newsroom/channels/attach/airbnb-report.pdf).
5. Chapple, K. (2009), *Mapping Susceptibility to Gentrification: The Early Warning Toolkit*, Centre for Community Innovation; [URL](https://communityinnovation.berkeley.edu/publications) 

The last of these is bit more 'academic' in tone but still intended to be very accessible to a lay-reader (i.e. non-expert).

## Possible Topics

Students are free to select a narrower or different focus of their briefing; for example, they may wish to develop the evidence either for/against the regulation of listings on Airbnb in London, but the briefing should **reference existing policies**, where relevant, and **may make recommendations** based on the analysis undertaken. These are *indicative* topics and you should feel free to strike out if some other aspect of the topic and data interest you:

- **Impact of Airbnb on local area rental markets** — this would require some assumptions about listings and lettings based on available data but as long as these are clearly stated this would be a strong approach; there are good examples of models used in other cities that it may be possible to draw on, or adapt to, London. You may want to consider things like the type of listing and the issues around the Short- and Long-Term Rental markets.
- **Impact of Airbnb on London's Tourism Economy** — this would look at the distribution of London's tourism venues and, possibly, hotels alongside Airbnb listings in order to evaluate the extent to which tourism 'dollars' *might* be spent in ways that positively impact less tourist-oriented areas if we assume (again, detail the assumptions) that some percentage of a tourist's dollars are spent locally in an area. Again, there may be models developed elsewhere that could be adapted for the London context.
- **Opportunities and Risks arising from Covid-19** — it should/may be possible to assess the impact of Covid-19 on London's short- and long-term rental markets by looking at entry to/exit from the Airbnb marketplace by comparing more than one snapshot of London data. Again, this will require some reasonable assumptions to be drawn (are all flats withdrawn from Airbnb going back on to the Long-Term Rental Sector?) but these can be documented and justified.
- **Opportunities for Place- or Listing-Branding** — identifying key terms and features/amenities used to market listings by area and using these to identify opportunities for investment or branding. This would benefit from the use of NLP approaches and, potentially, word embeddings to identify distinctive patterns of word use as well as, potentially, One-Hot encoding to identify specific amenities that appear associated in some way with particular areas.
- **The Challenge of Ghost Hotels** — evaluating ways to automatically identify ghost hotels from the InsideAirbnb data and then, potentially, assessing their extent and impact on local areas where they dominate either 'proper' hotel provision or other types of listings. You will need to consider the way that Airbnb randomly shuffles listings to prevent exactly this type of application and textual similarity via NLP is an obvious application.
- **The Professionalisation of Airbnb** — this could be treated either as a regulatory challenge (is Airbnb not benefiting locals) or an investment opportunity (is this a way to 'scale' or develop new service offers for small hosts) depending on your interests. You will need to consider the different types of hosts and evaluate ways of distinguishing between them (e.g. number of listings, spatial extent, etc.).
- **Impact Profiles** — a geodemographic classification of London neighbourhoods based on how they have, or have not, been impacted by Airbnb. This would require you to think about how to develop a classification/clustering of London neighbourhoods and use data to develop 'pen portraits' of each so that policy-makers could better-understand the range of environments in which Airbnb operates and why a 1-size-fits-all regulatory approach may be insufficient. Again, this could be argued from either standpoint or even both simultaneously: these areas are already so heavily impacted that regulation is too little, too late, while these other areas are 'at risk'.

## Partial Bibliography

You will also want to review the partial bibliography [available here](https://github.com/jreades/i2p/blob/master/bib/Bibliography.md); this is by no means complete and you will likely find other relevant work 'out there' but you may find it useful for spurring your thinking on what to study and how to study it. You might also want to have a look at guidance for London:

- KeyNest (2019), *Understanding Airbnb regulations in London*, KeyNest; [URL](https://keynest.com/blog/airbnb-regulations-london)
- Airbnb (n.d.), *I rent out my home in London. What short-term rental laws apply?*, Airbnb; [URL](https://www.airbnb.co.uk/help/article/1340/)i-rent-out-my-home-in-london-what-shortterm-rental-laws-apply
- Hostmaker (2018), *Important Airbnb regulations and laws you should know about in London*, Hostmaker; [URL](https://hostmaker.com/blog/important-airbnb-regulations-country-laws-know-london/)

