---
title: "Group Self-Evaluation"
---

This individual reflection and peer mark assessment ({{< var assess.peer-weight >}})  due {{< var assess.peer-date >}} (@{{< var assess.peer-time >}}) asks you to reflect *on the process* of 'doing data science' as part of a team, since this format is typical of real-world projects. Many companies (e.g. Apple, Google, etc.) employ an Agile project format in which teams undertake a 'Retrospective' at the end of a project in order to identify ways to improve how they work in the future. We are *not* asking you to do this as a group (indeed, it's an *individual* reflection), but we hope that this will help you to develop as a budding analyst or data scientist.

## Format

{{< include _self.qmd >}}

You will then be asked to score the *rest* of the group on their contribution to the project. You should be doing this with an eye both to contributions that may be more or less visible (*e.g.* someone who wrote the code may be more visible than the person who ensured that the code was answering the set question) as well as to the fact that you're much more likely to be aware of your own contributions than you are of the contributions of others.

The guidance for this is:

{{< include _peer.qmd >}}

## Restrictions

There is no word limit for the formative parts of the assessment, but as an indication ca. 125 words should be enough for a brief, thoughtful engagement. Together with the GitHub repo history, the formative component is the principal source of evidence we will take into account in the event of discrepancies in the group self-evaluation (aka. peer mark).

