---
title: "Group Self-Evaluation"
---

This individual reflection and peer mark assessment ({{< var assess.peer-weight >}})  due {{< var assess.peer-date >}} (@{{< var assess.peer-time >}}) asks you to reflect *on the process* of 'doing data science' as part of a team, since this format is typical of real-world projects. Many companies (e.g. Apple, Google, etc.) employ an Agile project format in which teams undertake a 'Retrospective' at the end of a project in order to identify ways to improve how they work in the future. We are *not* asking you to do this as a group (indeed, it's an *individual* reflection), but we hope that this will help you to develop as a budding analyst or data scientist.

## Format

{{< include _peer.qmd >}}

## Restrictions

There is no word limit for the formative parts of the assessment, but as an indication ca. 125 words should be enough for a brief, thoughtful engagement. The formative component is optional, but it is the sole evidence we will take into account in the event of discrepancies in the group self-evaluation (aka. peer mark).

