# Computer Health Check

Please ensure that your computer is fully up-to-date with Operating System and application updates before following any of the *other* steps in this brief guide to getting started. When answering these questions, 'your computer' is the machine on which you plan to do the programming. You will also have some ability to run code remotely on UCL's JupyterHub or on Google Collab, but you will find that limitations in processing power on these two platforms may make this a sometimes frustrating experience.

## General Guidance

We try to support as many different configurations as possible, but there is *no* programming environment that installs and runs seamlessly on *all* computers. However, in our experience the students **most likely to encounter problems** share one or more of the following:

1. Your computer runs Windows 10 Home or older, or MacOS 10.13 (High Sierra) or older.
2. Your computer 8GB or less of RAM.
3. Your computer has less than 15GB of free disk space remaining.

Read on below to check what specification you have...

If you are looking for a recommendation as to what to buy:

1. Don't worry about getting the fastest chip, get the most RAM. You should aim for 32GB of RAM, but get more if you can afford it.
2. Don't worry about getting the biggest hard drive, get the fastest one. You should get a SSD (Solid State Drive), but get a M2 type SSD if you can afford it and it's available for your system.
3. Only once you've sorted this out should you look for the fastest chipset that's still within your budget.

## MacOS

- What Operating System and Version is your _main_ computer running? [Help for Mac](https://support.apple.com/en-gb/HT201260).
- How much RAM does your _main_ computer have? [Help for Mac](https://www.macworld.co.uk/how-to/mac/much-ram-need-more-3793418/).
- How much free disk space does your _main_ computer have? [Help for Mac](https://www.macworld.com/article/2972775/how-to-check-a-mac-free-hard-drive-space.html).

## Windows

- What Operating System and Version is your _main_ computer running? [Help for Windows](https://support.microsoft.com/en-gb/help/13443/windows-which-version-am-i-running).
- How much RAM does your _main_ computer have? [Help for Windows](https://www.howtogeek.com/435644how-to-see-how-much-ram-is-in-your-pc-and-its-speed/).
- How much free disk space does your _main_ computer have? [Help for Windows](https://www.lifewire.com/how-to-check-free-hard-drive-space-in-windows-2619187).

## Linux

We're going to assume that you know what you're doing. If you want a recommendation, we'd probably go with the latest Ubuntu desktop release.
