# Getting Started

In order to get you started on your data science 'journey' you will need to follow the guidance provided on the pages we've linked to below from the [CASA Computing Environment](https://jreades.github.io/sds_env/) web site.

## Requirements {#sec-requirements}

Before trying to do anything else please complete the basic [health check](https://jreades.github.io/sds_env/req/health.html), which also includes our *recommendations* if you are considering buying a new computer when you start your studies. Once you know that your machine and operating system are up-to-date, you should install the [basic utilities](https://jreades.github.io/sds_env/req/base.html) that will enable you to complete installation of the programming environment. We also provide information about [Code Camp](https://jreades.github.io/sds_env/req/code_camp.html) which is a self-paced introduction to the fundamentals of programming in Python.

## Setup

Once you've ticked off the Requirements, you can start installing the tools that you will use to write and run both code and documentation. You will need to:

1. Did you set up the [Base Utilities](https://jreades.github.io/sds_env/req/base.html) linked to in @sec-requirements (Requirements) above? 
2. Install and configure [Git and GitHub](https://jreades.github.io/sds_env/setup/git.html) in order to manage, share, and version code. 
3. Install a [Markdown](https://jreades.github.io/sds_env/setup/markdown.html) editor and familiarise yourself with Markdown's syntax in order to write documentation, comments, and the Group Submission. 
4. Install the [programming environment](https://jreades.github.io/sds_env/setup/env.html), including [Docker](https://jreades.github.io/sds_env/setup/env.html#docker) and, potentially, [VSCode](https://jreades.github.io/sds_env/setup/env.html#vscode).

::: {.callout-warning}

In an emergency, as a backup some part of the term will work with the ['no install' option](https://jreades.github.io/sds_env/setup/no_install.html) or [Anaconda Python](https://jreades.github.io/sds_env/setup/env.html#anaconda-python), but this will make your life significantly harder if it is your first choice as we are unable to provide support for these.

:::

## Soft Skills

Over the years, based on student experience and feedback we have collected a range of advice that is not purely technical in nature. This section covers [managing distractions](https://jreades.github.io/sds_env/skills/attention.html), an introduction to [how to read](https://jreades.github.io/sds_env/skills/reading.html) (in the academic sense of reading journal articles and books for *meaning* and *relevance*) as well as [how to think](https://jreades.github.io/sds_env/skills/thinking.html) (in the sense of why the modules are the way they are and the importance of reflection), and [how to ask for help](https://jreades.github.io/sds_env/skills/help.html) (because that's what we're to do, but first you need to help yourself!).